// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lekhloppxkvtwkxtsetv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxla2hsb3BweGt2dHdreHRzZXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzEzNDQsImV4cCI6MjA2MTA0NzM0NH0.J5pEwJ9jLaGJtxkBJxQeqjV90OxoUNxfJUQui5uMwEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);